name: Build as content_shell and upload ipa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install depot_tools
      run: |
        cd $HOME
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$HOME/depot_tools" >> $GITHUB_PATH

    - name: Fetch Chromium Source
      run: |
        cd $HOME
        mkdir -p ~/chromium && cd ~/chromium
        fetch --no-history ios 
        cd src
        gclient sync

    - name: Generate Build Files
      run: |
        cd ~/chromium/src
        gn gen out/Release --args='is_debug=false target_os="ios" ios_enable_code_signing=false target_cpu="arm64" is_debug=false use_blink=true'

    - name: Build Chromium for iOS
      run: |
        cd ~/chromium/src
        autoninja -C out/Release content_shell

    - name: Create .ipa File
      run: |
        cd ~/chromium/src/out/Release
        mkdir -p Payload
        cp -r ios_internal_app.app Payload/
        zip -r chromium.ipa Payload

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: ~/chromium/src/out/Release/chromium.ipa
